In [1]:
pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.4.60-py3-none-any.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.13.0.92)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.11.0+cu128)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.26.0+cu128)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.35.2)
Collecting ultralytics-thop>=2.0.18 (from ultralytics)
  Downloading ultralytics_thop-2.0.19-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.20.0->ultralytics) (1.35.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2026.5.20)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.9.6)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.8.0->ultralytics) (1.5.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Downloading ultralytics-8.4.60-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 26.6 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.19-py3-none-any.whl (28 kB)
Installing collected packages: ultralytics-thop, ultralytics
Successfully installed ultralytics-8.4.60 ultralytics-thop-2.0.19

In [14]:
!find /content/test_dataset -type f

/content/test_dataset/data.yaml
/content/test_dataset/labels/95_JPG_jpg.rf.5e6fdbdb0565ef174e841c5439ec745a.txt
/content/test_dataset/labels/00048_jpg.rf.65a252196defed676f4b1940fae3eec5.txt
/content/test_dataset/labels/00126_jpg.rf.4e369744d8de242d783ae6281f4fcf95.txt
/content/test_dataset/labels/00121_jpg.rf.a2c8327479b4d3b52c461bb39737d5ea.txt
/content/test_dataset/labels/00100_jpg.rf.87e0894580a4f957424704b89d2d1451.txt
/content/test_dataset/labels/20220721_124131_jpg.rf.3ac4cd2c3d149f9c37611dfc54dee3d9.txt
/content/test_dataset/labels/00011_jpg.rf.f0172773f4f585fab51e32c2fdb6c189.txt
/content/test_dataset/labels/00137_jpg.rf.916ffb2c796f45d33d968b12168393b5.txt
/content/test_dataset/labels/00121_jpg.rf.d82da9da25666ed33ff7915715aa32cf.txt
/content/test_dataset/labels/00121_jpg.rf.7c441e991513d70ff9e83ce51f6cb0dc.txt
/content/test_dataset/labels/00225_jpg.rf.7d2cf6cebb762dcf94ab0ef005be27b7.txt
/content/test_dataset/labels/00125_jpg.rf.79288745cdd2cc079c01ad6f9625bfd6.txt
/content/test_dataset/labels/4843_RolePlay_ConstructionWorker_BoyGirl_jpg.rf.6049111316c3565e6b9c923e94d46a8a.txt
/content/test_dataset/labels/95_JPG_jpg.rf.d91ec768d37bbdacd56534739f083b30.txt
/content/test_dataset/labels/00126_jpg.rf.618933aacce7c3de566664d7d12db5b4.txt
/content/test_dataset/labels/00350_jpg.rf.7accc290fa74ac8db223e692cb30e231.txt
/content/test_dataset/labels/105_JPG_jpg.rf.845a99aacf472fd76f1dda6ceb2e88d9.txt
/content/test_dataset/labels/00122_jpg.rf.3c75b5c5bd1126dd7a32c21e5dc41caa.txt
/content/test_dataset/labels/20220721_161927_jpg.rf.65f09d4cc7008da6304f276bfac7b5a0.txt
/content/test_dataset/labels/00121_jpg.rf.7479b44c742de497acf7d4ec8225e9a5.txt
/content/test_dataset/images/00121_jpg.rf.d82da9da25666ed33ff7915715aa32cf.jpg
/content/test_dataset/images/00121_jpg.rf.7c441e991513d70ff9e83ce51f6cb0dc.jpg
/content/test_dataset/images/00121_jpg.rf.a2c8327479b4d3b52c461bb39737d5ea.jpg
/content/test_dataset/images/20220721_161927_jpg.rf.65f09d4cc7008da6304f276bfac7b5a0.jpg
/content/test_dataset/images/00121_jpg.rf.7479b44c742de497acf7d4ec8225e9a5.jpg
/content/test_dataset/images/105_JPG_jpg.rf.845a99aacf472fd76f1dda6ceb2e88d9.jpg
/content/test_dataset/images/00137_jpg.rf.916ffb2c796f45d33d968b12168393b5.jpg
/content/test_dataset/images/00122_jpg.rf.3c75b5c5bd1126dd7a32c21e5dc41caa.jpg
/content/test_dataset/images/95_JPG_jpg.rf.5e6fdbdb0565ef174e841c5439ec745a.jpg
/content/test_dataset/images/00125_jpg.rf.79288745cdd2cc079c01ad6f9625bfd6.jpg
/content/test_dataset/images/00350_jpg.rf.7accc290fa74ac8db223e692cb30e231.jpg
/content/test_dataset/images/00126_jpg.rf.4e369744d8de242d783ae6281f4fcf95.jpg
/content/test_dataset/images/00126_jpg.rf.618933aacce7c3de566664d7d12db5b4.jpg
/content/test_dataset/images/00011_jpg.rf.f0172773f4f585fab51e32c2fdb6c189.jpg
/content/test_dataset/images/4843_RolePlay_ConstructionWorker_BoyGirl_jpg.rf.6049111316c3565e6b9c923e94d46a8a.jpg
/content/test_dataset/images/00048_jpg.rf.65a252196defed676f4b1940fae3eec5.jpg
/content/test_dataset/images/00225_jpg.rf.7d2cf6cebb762dcf94ab0ef005be27b7.jpg
/content/test_dataset/images/95_JPG_jpg.rf.d91ec768d37bbdacd56534739f083b30.jpg
/content/test_dataset/images/20220721_124131_jpg.rf.3ac4cd2c3d149f9c37611dfc54dee3d9.jpg
/content/test_dataset/images/00100_jpg.rf.87e0894580a4f957424704b89d2d1451.jpg

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [18]:
!pip install ultralytics pandas matplotlib seaborn openpyxl -q

In [22]:
!ls -R /content/test_dataset

/content/test_dataset:
data.yaml  images  labels

/content/test_dataset/images:
00011_jpg.rf.f0172773f4f585fab51e32c2fdb6c189.jpg
00048_jpg.rf.65a252196defed676f4b1940fae3eec5.jpg
00100_jpg.rf.87e0894580a4f957424704b89d2d1451.jpg
00121_jpg.rf.7479b44c742de497acf7d4ec8225e9a5.jpg
00121_jpg.rf.7c441e991513d70ff9e83ce51f6cb0dc.jpg
00121_jpg.rf.a2c8327479b4d3b52c461bb39737d5ea.jpg
00121_jpg.rf.d82da9da25666ed33ff7915715aa32cf.jpg
00122_jpg.rf.3c75b5c5bd1126dd7a32c21e5dc41caa.jpg
00125_jpg.rf.79288745cdd2cc079c01ad6f9625bfd6.jpg
00126_jpg.rf.4e369744d8de242d783ae6281f4fcf95.jpg
00126_jpg.rf.618933aacce7c3de566664d7d12db5b4.jpg
00137_jpg.rf.916ffb2c796f45d33d968b12168393b5.jpg
00225_jpg.rf.7d2cf6cebb762dcf94ab0ef005be27b7.jpg
00350_jpg.rf.7accc290fa74ac8db223e692cb30e231.jpg
105_JPG_jpg.rf.845a99aacf472fd76f1dda6ceb2e88d9.jpg
20220721_124131_jpg.rf.3ac4cd2c3d149f9c37611dfc54dee3d9.jpg
20220721_161927_jpg.rf.65f09d4cc7008da6304f276bfac7b5a0.jpg
4843_RolePlay_ConstructionWorker_BoyGirl_jpg.rf.6049111316c3565e6b9c923e94d46a8a.jpg
95_JPG_jpg.rf.5e6fdbdb0565ef174e841c5439ec745a.jpg
95_JPG_jpg.rf.d91ec768d37bbdacd56534739f083b30.jpg

/content/test_dataset/labels:
00011_jpg.rf.f0172773f4f585fab51e32c2fdb6c189.txt
00048_jpg.rf.65a252196defed676f4b1940fae3eec5.txt
00100_jpg.rf.87e0894580a4f957424704b89d2d1451.txt
00121_jpg.rf.7479b44c742de497acf7d4ec8225e9a5.txt
00121_jpg.rf.7c441e991513d70ff9e83ce51f6cb0dc.txt
00121_jpg.rf.a2c8327479b4d3b52c461bb39737d5ea.txt
00121_jpg.rf.d82da9da25666ed33ff7915715aa32cf.txt
00122_jpg.rf.3c75b5c5bd1126dd7a32c21e5dc41caa.txt
00125_jpg.rf.79288745cdd2cc079c01ad6f9625bfd6.txt
00126_jpg.rf.4e369744d8de242d783ae6281f4fcf95.txt
00126_jpg.rf.618933aacce7c3de566664d7d12db5b4.txt
00137_jpg.rf.916ffb2c796f45d33d968b12168393b5.txt
00225_jpg.rf.7d2cf6cebb762dcf94ab0ef005be27b7.txt
00350_jpg.rf.7accc290fa74ac8db223e692cb30e231.txt
105_JPG_jpg.rf.845a99aacf472fd76f1dda6ceb2e88d9.txt
20220721_124131_jpg.rf.3ac4cd2c3d149f9c37611dfc54dee3d9.txt
20220721_161927_jpg.rf.65f09d4cc7008da6304f276bfac7b5a0.txt
4843_RolePlay_ConstructionWorker_BoyGirl_jpg.rf.6049111316c3565e6b9c923e94d46a8a.txt
95_JPG_jpg.rf.5e6fdbdb0565ef174e841c5439ec745a.txt
95_JPG_jpg.rf.d91ec768d37bbdacd56534739f083b30.txt

In [23]:
with open("/content/test_dataset/data.yaml", "w") as f:
    f.write("""
path: /content/test_dataset

train: images
val: images
test: images

nc: 10

names:
  0: boots
  1: gloves
  2: goggles
  3: helmet
  4: no-boots
  5: no-gloves
  6: no-goggles
  7: no-helmet
  8: no-vest
  9: vest
""")

In [24]:
from ultralytics.data.utils import check_det_dataset

check_det_dataset("/content/test_dataset/data.yaml")

Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 24.4MB/s 0.0s

{'path': PosixPath('/content/test_dataset'),
 'train': '/content/test_dataset/images',
 'val': '/content/test_dataset/images',
 'test': '/content/test_dataset/images',
 'nc': 10,
 'names': {0: 'boots',
  1: 'gloves',
  2: 'goggles',
  3: 'helmet',
  4: 'no-boots',
  5: 'no-gloves',
  6: 'no-goggles',
  7: 'no-helmet',
  8: 'no-vest',
  9: 'vest'},
 'yaml_file': '/content/test_dataset/data.yaml',
 'channels': 3}

In [26]:
for name, path in MODELS.items():
    model = YOLO(path)
    print(name)
    print(model.names)
    print("-"*50)

Model1
{0: 'Gloves', 1: 'Vest', 2: 'goggles', 3: 'helmet', 4: 'mask', 5: 'safety_shoe'}
--------------------------------------------------
Model2
{0: 'barricade', 1: 'dumpster', 2: 'excavators', 3: 'gloves', 4: 'hardhat', 5: 'mask', 6: 'no-hardhat', 7: 'no-mask', 8: 'no-safety vest', 9: 'person', 10: 'safety net', 11: 'safety shoes', 12: 'safety vest', 13: 'dump truck', 14: 'mini-van', 15: 'truck', 16: 'wheel loader'}
--------------------------------------------------
Model3
{0: 'Fall-Detected', 1: 'Gloves', 2: 'Goggles', 3: 'Hardhat', 4: 'Ladder', 5: 'Mask', 6: 'NO-Gloves', 7: 'NO-Goggles', 8: 'NO-Hardhat', 9: 'NO-Mask', 10: 'NO-Safety Vest', 11: 'Person', 12: 'Safety Cone', 13: 'Safety Vest'}
--------------------------------------------------

In [27]:
from ultralytics import YOLO
import os
import glob
import pandas as pd
import numpy as np
from collections import defaultdict

In [28]:
MODELS = {
    "Model1": "/content/models/model1.pt",
    "Model2": "/content/models/model2.pt",
    "Model3": "/content/models/model3.pt"
}

IMG_DIR = "/content/test_dataset/images"
LBL_DIR = "/content/test_dataset/labels"

SAVE_DIR = "/content/drive/MyDrive/PPE_Model_Comparison"

os.makedirs(SAVE_DIR, exist_ok=True)

In [29]:
# Dataset classes
GT_MAP = {
    1: "gloves",
    3: "helmet",
    9: "vest"
}

MODEL_MAP = {
    "Model1": {
        "Gloves": "gloves",
        "helmet": "helmet",
        "Vest": "vest"
    },

    "Model2": {
        "gloves": "gloves",
        "hardhat": "helmet",
        "safety vest": "vest"
    },

    "Model3": {
        "Gloves": "gloves",
        "Hardhat": "helmet",
        "Safety Vest": "vest"
    }
}

In [30]:
def load_gt(label_file):

    objs = []

    with open(label_file) as f:
        lines = f.readlines()

    for line in lines:

        parts = line.strip().split()

        cls = int(parts[0])

        if cls in GT_MAP:
            objs.append(GT_MAP[cls])

    return objs

In [32]:
results = []

for model_name, model_path in MODELS.items():

    print("\nEvaluating", model_name)

    model = YOLO(model_path)

    TP = defaultdict(int)
    FP = defaultdict(int)
    FN = defaultdict(int)

    image_paths = sorted(glob.glob(f"{IMG_DIR}/*.jpg"))

    for img_path in image_paths:

        label_path = os.path.join(
            LBL_DIR,
            os.path.basename(img_path).replace(".jpg",".txt")
        )

        gt = load_gt(label_path)

        pred = []

        res = model.predict(
            img_path,
            conf=0.25,
            verbose=False
        )

        for c in res[0].boxes.cls.cpu().numpy():

            cls_name = model.names[int(c)]

            if cls_name in MODEL_MAP[model_name]:
                pred.append(
                    MODEL_MAP[model_name][cls_name]
                )

        gt_set = set(gt)
        pred_set = set(pred)

        for cls in ["helmet","gloves","vest"]:

            if cls in gt_set and cls in pred_set:
                TP[cls] += 1

            elif cls not in gt_set and cls in pred_set:
                FP[cls] += 1

            elif cls in gt_set and cls not in pred_set:
                FN[cls] += 1

    rows = []

    macro_f1 = []

    for cls in ["helmet","gloves","vest"]:

        tp = TP[cls]
        fp = FP[cls]
        fn = FN[cls]

        precision = tp/(tp+fp+1e-9)
        recall    = tp/(tp+fn+1e-9)

        f1 = 2*precision*recall/(precision+recall+1e-9)

        macro_f1.append(f1)

        rows.append([
            model_name,
            cls,
            tp,
            fp,
            fn,
            precision,
            recall,
            f1
        ])

    df = pd.DataFrame(
        rows,
        columns=[
            "Model",
            "Class",
            "TP",
            "FP",
            "FN",
            "Precision",
            "Recall",
            "F1"
        ]
    )

    df.to_csv(
        f"{SAVE_DIR}/{model_name}_metrics.csv",
        index=False
    )

    results.append({
        "Model": model_name,
        "Macro_F1": np.mean(macro_f1)
    })

Evaluating Model1

Evaluating Model2

Evaluating Model3

In [33]:
ranking = pd.DataFrame(results)

ranking = ranking.sort_values(
    by="Macro_F1",
    ascending=False
)

ranking

    Model  Macro_F1
2  Model3  0.462121
0  Model1  0.266667
1  Model2  0.166667

In [34]:
ranking.to_csv(
    f"{SAVE_DIR}/final_ranking.csv",
    index=False
)

ranking

    Model  Macro_F1
2  Model3  0.462121
0  Model1  0.266667
1  Model2  0.166667

In [35]:
best = ranking.iloc[0]

print("="*50)
print("BEST MODEL")
print("="*50)

print(best["Model"])
print("Macro F1 =", best["Macro_F1"])

==================================================
BEST MODEL
==================================================
Model3
Macro F1 = 0.4621212117385502